import type { Metadata } from "next";
import { ThemeProvider } from "@/components/ThemeProvider";
import "../themes/global.css";
import { pageWrapper } from "./layout.css";
import { Footer } from "./Footer";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <ThemeProvider>
          <div className={pageWrapper}>{children}</div>
          <Footer />
        </ThemeProvider>
      </body>
    </html>
  );
}
